### ISSUE TITLE
Ham-mode unusable on Windows platform

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/ham-mode#4]
# Bug report

## Setup:
GNU Emacs GUI version 25.0.5.1 (x86_64-w64-mingw32) 
[Compiled from Harroogan Emacs.](https://bitbucket.org/Haroogan/emacs-for-windows/)
Ham-mode, using the latest version of ham-mode from MELPA
Windows 7 x64 bit.

## Situation:
When I activate `ham-mode` on HTML-page, then I save the contents, I get an error. Messages buffer gives me the following:

    Saving file a:/Dropbox/Emacs/foobar.html...
    Wrote a:/Dropbox/Emacs/foobar.html
    ham-mode--run-conversion: Can't find the markdown executable! Is it installed? See `command'. 

So it seems I need to have `markdown` executable. When Looking up `C-f ham-mode`, and then I found one related to `command`.

    ham-mode-markdown-to-html-command is a variable defined in ‘ham-mode.el’.
    Its value is (nil file)

    This variable may be risky if used as a file-local variable.

    Documentation:
    Command used to convert markdown contents into hmtl.

    This variable is a list:
    - First element is the full path to the markdown executable.
    - Other elements are either the symbol 'file (replaced with the
        filename) or strings (arguments to the passed to the executable).

    Unfortunately, this variable depends on the implementation so you
    might have to tweak it. Some versions of the markdown command
    need an "--html4tags" argument in order to produce the right
    output, while other versions will give an error if you pass them
    that argument.
    Meanwhile, other implementations require that you specifically
    enable some features.

    If your executable isn't generating good results (some don't
    support all features) you can try to install pandoc and set this
    variable to:

        '("pandoc" "--from" "markdown" "--to" "html" file)

    You can customize this variable.

    This variable was introduced, or its default value was changed, in
    version 1.1.1 of the ham-mode package.

It seems there is no markdown executable available for Windoes platform. So I try pandoc. 

After installing it, I verifiy the installation in my Windows shell. It works, I get a message telling me which version of pandoci is installed. 

After reading the Pandoc documenation, I set the following variable given the documentation of `ham-mode-markdown-to-html-command`.

    (setq ham-mode-markdown-to-html-command "pandoc -f markdown -t html")

Evaluate it, and go to the ham-buffer. Type some Markdown markup, then saving it.

Then I got this error message: 

    ham-mode--save-as-html: Wrong type argument: listp, "pandoc --from markdown --to html file"

Another suggestions?

**Comment by Malabarba** [comment]
You need to set the variable to a list. The first element is the executable, the rest are the string arguments. It also needs to contain the `file` symbol somewhere, which will be used internally as the name of the markdown file.

So try the following:

    (setq ham-mode-markdown-to-html-command '("pandoc" "-f" "markdown" "-t" "html" file))

**Comment by ReneFroger** [comment]
Thanks for your reply, after evaluating 

    (setq ham-mode-markdown-to-html-command '("pandoc" "-f" "markdown" "-t" "html" file))


And saving the file in Ham-mode, I get the same message:


    Wrote a:/Dropbox/foobar.html
    ham-mode--run-conversion: Can't find the markdown executable! Is it installed? See `command'

After restarting, I still have the same problem. So there must be a switcher, that use the `ham-mode-markdown-to-html-command` instead the default command.

I found the variable `ham-mode-markdown-command`, but this seems to be an alias for `ham-mode-markdown-to-html-command`.

So another suggestion?

**Comment by Malabarba** [comment]
Type `M-:` and run `(executable-find "pandoc")`, do you get anything?

**Comment by ReneFroger** [comment]
No, `nil` is the only answer that I get in the minibuffer. Same with after evaluating `(setq ham-mode-markdown-to-html-command '("pandoc" "-f" "markdown" "-t" "html" file))` and even after restaring emacs with the new settings initialized.

**Comment by Malabarba** [comment]
Ok, then it's not about ham-mode. The problem is that emacs doesn't see your pandoc executable. The executable is probably not in your path.

You can probably solve this by adding the executable's directory to you PATH, but a simpler solutionis to write the full path instead of `"pandoc"` in the variable configuration.

**Comment by ReneFroger** [comment]
I placed the pandoc binaries into my PATH, more spefically in my Vim74 folder, where the rest of binaries lays that are called with the PATH. I restarted my pc. 

And  then `M-: (executable-find "pandoc")`, I get the the path (it's `A:/Dropbox/Vim/vim74/pandoc.exe`). 

Even when saving, I get the same error. So I assume I need to write the full path down to this way:

`(setq ham-mode-markdown-to-html-command '("A:/Dropbox/Vim/vim74/pandoc.exe" "-f" "markdown" "-t" "html" file))`

If I'm right?

**Comment by Malabarba** [comment]
Sorry, that part was a bug in ham-mode. It should work now just by using:

```
(setq ham-mode-markdown-to-html-command '("pandoc" "-f" "markdown" "-t" "html" file))
```

However, please keep in mind that I'm not sure if your method will work. You copied the `pandoc.exe` file to another directory in your load-path, but that could fail if pandoc expects some other file to be inside its directories (like some config or some linked dll).
The proper way of setting path in Windows is by editing you environment variables.
